name: Publish Canary Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/on-push-lint-charts.yml'
      - '.github/workflows/on-push-master-publish-chart.yml'
      - '.github/workflows/runners.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/test-entrypoint.yml'
      - '.github/renovate.*'
      - 'runner/**'
      - '.gitignore'
      - 'PROJECT'
      - 'LICENSE'
      - 'Makefile'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish Canary Image
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Environment
        id: vars
        uses: ./.github/actions/setup-docker-environment
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          ghcr_username: ${{ github.actor }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      # Considered unstable builds
      # See Issue #285, PR #286, and PR #323 for more information
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/actions-runner-controller:canary
          cache-from: type=gha
          cache-to: type=gha,mode=max
